### PR TITLE
`ContainSubtree` constraint

### PR DESCRIPTION
**Pull request by BalassaMarton**
This constraint will match a JSON document against a subtree. This is useful when verifying JSON data, and multiple but not all properties of an object must be compared against known values.
Example: I am testing some CRUD web service, have a response like this:
```js
{
  success: true,
  data: {
    id: 123,
    name: 'Foo',
    type: 'my-type',
    someOtherProperty: 'asd'
  }
}
```
...and I want to assert that the request succeeded and the returned object has type `my-type` with name `Foo`. The other properties are irrelevant and/or unknown. Without this assertion, I'd have to write something like this:
```cs
response["success"].Should().HaveValue(true);
response["data"]["type"].Should().HaveValue("my-type");
response["data"]["name"].Should().HaveValue("Foo");
```
Yuck! The same test can be done with a single call using `ContainSubtree`:
```cs
response.Should().ContainSubtree(JToken.Parse(" { success: true, data: { type: 'my-type', name: 'Foo' }  } "));
```
When using with arrays, the assertion is that the JSON array under testing must contain a matching element for each of the elements in the subtree array, eg. this should fail:
```
var json = JToken.Parse("[ { name: 'Alpha' }, { name: 'Bravo' }, { name: 'Charlie' } ]");
json.Should().ContainSubtree(JToken.Parse("[ { name: 'Alpha' }, { name: 'Delta' } ]"));
```

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Sorry, I missed this PR. Would you be willing to rebase on the `release-5.0` hot-fix branch?

**Comment by BalassaMarton** [comment]
Hi, sure, as soon as I learn how to do that :)

**Comment by dennisdoomen** [comment]
https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase :-)

**Comment by BalassaMarton** [comment]
I did a rebase althouth I'm not sure it worked. Can you look at it? I also commited the nuspec, please ignore it when merging.

**Comment by dennisdoomen** [comment]
Apparently you forgot to change the target branch to release 5.0. I didn't see that and accidentally merged this change. I'm currently merging 5.0 to _master_, so I'll ping you to re-apply the change later on

**Pull request merged**
